### ISSUE TITLE
Previest domenu openstreetmap.sk na Freemap

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-operations#10]
Chlapik povedal ze ked budeme local chapter tak do prevedie

**Comment by kaylesk** [comment]
Idem to skúsiť vybaviť.

**Comment by zdila** [comment]
jasom cakal kym to budeme mat aj podpisane :-)

**Comment by kaylesk** [comment]
Držiteľ domény zmenený na Freemap Slovakia.
