### ISSUE TITLE
Nový routing pre turistiku

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-operations#12]
Nemáme vlastný routing pre turistiku (mali sme, ale "odhnil").

Návrh - Graphhopper.

Ak sa osvedci, tak aj pre cyklo a pod...

**Comment by jose1711** [comment]
Ako su na tom ostatne routery? Co znamena "odhnil"? Su tam nahrane data k nejakemu dnu a uz sa dalej neaktualizuje?

**Comment by zdila** [comment]
Ostatne routery funguju. Ten pre turistiku sa neaktualizuje uz takmer rok a rieseniu ako spustit aktualizaciu nie je navod (asi to vie iba MP ktory je uz neaktivny).

**Comment by alexanderzatko** [comment]
toto uz asi nie je aktualna uloha, kedze GH uz mame implementovany?

**Comment by zdila** [comment]
pravda. ale tu sa aj tak nikto nepozera :-)
