### ISSUE TITLE
Nakonfigurovat a nainstalovat greeter-osm

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-operations#15]
Nasi kolegovia z Ceska maju [sikovne riesenie](https://github.com/osmcz/greeter-osm), ktore posle novemu OSM prispievatelovi z Ceska uvitaci email. Myslim ze by bolo dobre toto nainstlovat aj na freemap server. Ak to niekto nainstaluje, tak mozem prelozit do slovenciny a upravit samotnu spravu.

**Comment by zdila** [comment]
AFAIK toto uz mame a prave cesi sa inspirovali od nas. Riesil to tusim @jose1711

**Comment by jose1711** [comment]
> based on greeter_osmsk.py 0.7

Kolegovia z Ceska prevzali ten greeter od nas a upravili + vylepsili. Myslim, ze bezi na nasom serveri a pouziva moje credentials na posielanie privitania. Pozri tiez https://groups.google.com/g/osm_sk/c/VB4qOrg93cc/m/cbZkYHsZFrkJ

**Comment by alexanderzatko** [comment]
Aha, skvele. Mozno by bolo ale dobre skontrolovat ci sluzba este bezi, pretoze napriklad pouzivatel miklosakos co som s nim riesil nedavno zmeny na Krupinskej akoby netusil o existencii mailing listu. Ale na druhej strane mozno nemonitoroval email s ktorym sa prihlasil, kedze spociatku nereagoval na komentare v changesetoch.

**Comment by jose1711** [comment]
miklosakos mapuje od 2013. privitacie spravy sa posielaju od 2015 a neposielali sa pouzivatelom, ktori sa registrovali v minulosti. aktualne vyzera, ze chodia:
![obrázok](https://user-images.githubusercontent.com/1406222/118391391-54ab5000-b634-11eb-875a-5454f48a08d6.png)

**Comment by alexanderzatko** [comment]
ok, dikes
