### ISSUE TITLE
Upozornit pouzivatelov s changesetom kde imagery_used="Bing aerial imagery"

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-operations#16]
Poslat mail ako si v iD nastavit pozadie "Ortofotomozaika SR" ak niekto v iD zedituje nieco na Slovensku a pozadie ma nastavene na "Bing aerial imagery" (pripadne este dalsie?).

**Comment by zdila** [comment]
@jose1711 vedel by si sa do toho prosim pustit?

**Comment by jose1711** [comment]
Skusam najst RSS feed s najnovsimi editmi na uzemi Slovenska, ale nejak sa nedari. Nevies o niecom? Alebo cerpat radsej z minutovych diffov?

**Comment by zdila** [comment]
neviem, s tym skusenost nemam. ale v minutovych diffoch to isto bude :-)
