### ISSUE TITLE
Novovestské traily

### ISSUE THREAD

**Issue by kaylesk** [FreemapSlovakia/freemap-operations#19]
Mapka podľa všetkého z OSM dát (vizualizácia asi vlastná?, pravdepodobne maperitive...)
https://www.freemap.sk/?map=15/48.948407/20.503106&layers=XI&image=331010

**Comment by kaylesk** [comment]
2.11.2021 zaslaný email na @mestosnv.sk ( referát cestovného ruchu a zahraničných vzťahov) a na @lesysnv.sk

**Comment by zdila** [comment]
Mapka je na 99% z [mapy.cz](https://sk.mapy.cz/turisticka?x=20.5203428&y=48.9005650&z=15). Som myslel ze poznas konkurenciu ;-).

**Comment by alexanderzatko** [comment]
mapy.cz su problemom aj pri tom linku ktory som ja spominal na fore: https://lesmir.sk/chodniky. ... a myslim ze takych pripadov dokazem najst viac ak by som sa trochu snazil. Co s tym @kaylesk a @andrewshadura?

**Comment by zdila** [comment]
Trochu offtopic, ale mapy.cz attributuju OSM nedostatocne. Minimalne na cz fore sa to uz riesilo.

**Comment by kaylesk** [comment]
Bolo mi to nejaké povedomé, ale nevedel som presne zaradiť. Popravde tak často na to nepozerám. (načo aj) Doplním text emailu s tím nech tam spomenú aj seznam.cz
https://lesmir.sk/ prosím tu #20

**Comment by andrewshadura** [comment]
Zavolal som im a vysvetlil som, že môžu to vyriešiť nálepkou, a že freemap.sk má ešte krajšiu vizualizáciu :wink:

**Comment by kaylesk** [comment]
3.11.2021 reagovali  (firma čo pripravila tabuľu) Zašlem im potrebný text a zabezpečia.

**Comment by zdila** [comment]
Tak za OSM tam musí byť spomenuté OpenStreetMap, avšak vieš čo vyžadujú mapy.cz? Či vôbec povoľujú zadarmo šíriť ich mapy...

**Comment by andrewshadura** [comment]
Myslím si, že svoju atribúciu by mapy.cz mali strážiť sami :slightly_smiling_face:

**Comment by kaylesk** [comment]
https://licence.mapy.cz/?doc=mapy_pu
Povedal som im (telefonicky) že by mali spomenúť aj seznam a hodím im ešte raz link do emailu.

**Comment by zdila** [comment]
Vďaka. Chýba im tam teda logo mapy.cz. Ale riešiť to už je pre nás nadpráca (tj. zadarmo pre mapy.cz) :-)

**Comment by kaylesk** [comment]
18.11.2021 vybavené
