### ISSUE TITLE
Povolenia na a data pre import hranic pralesov

### ISSUE THREAD

**Issue by alexanderzatko** [FreemapSlovakia/freemap-operations#22]
Pisal som dopyt na pralesy.sk:

----------------------

From: Alexander Zatko <alexander.zatko@freemap.sk>
Subject: hranice pralesov
Date: 3 November 2021 at 21:06:43 CET
To: ozprales@gmail.com

Dobry den,

Som clen o.z. Freemap Slovakia, ktoreho cielom je mapovat (hlavne) Slovensko v ramci projektu Openstreetmap. Pisem vam preto, lebo som si vsimol, ze na vasej mape mate pekne znazornene hranice pralesov  Niektore z nich su aj v databaze projektu Openstreetmap, ale nie vsetky. Bolo by mozne tieto data od vas ziskat? Ak ano, viete mi povedat pod akou licenciou by to bolo mozne?_

----------------------

...a dnes som dostal odpoved:

----------------------

From: Marián Jasík
Subject: Pralesy
Date: 7 November 2021 at 11:55:29 CET
To: alexander.zatko@freemap.sk
Cc: Juraj Vysoky

Dobrý deň,

v prílohe posielam aktuálnu vrstvu pralesov a pralesových zvyškov. Bolo to spracované za verejné zdroje takže to posielame každému kto to chce/potrebuje.

----------------------

Prilohu pripajam, o licenciu na data este poziadam.

Skusal som to aj test-importnut do JOSM, ale zda sa ze bude treba tie data este pretransformovat do spravnej projekcie.

<img width="928" alt="Screenshot 2021-11-07 at 12 14 50" src="https://user-images.githubusercontent.com/3430677/140642714-e12a2f87-8d0a-43b0-8cd7-e71776e46cf1.png">

[pralesy_2021.zip](https://github.com/FreemapSlovakia/freemap-operations/files/7492143/pralesy_2021.zip)

**Comment by zdila** [comment]
Skus toto: [pralesy.geojson.gz](https://github.com/FreemapSlovakia/freemap-operations/files/7492179/pralesy.geojson.gz)

**Comment by alexanderzatko** [comment]
skvele

**Comment by alexanderzatko** [comment]
Prales, o.z. je podla odpovede p. Jasika vlastnikom dat, takze ja by som povazoval ich suhlas dany vyssie za dostatocny na import to databazy OSM.

-------------
From: Marián Jasík
Subject: Re: Pralesy
Date: 8 November 2021 at 08:13:51 CET
To: Alexander Zatko

Dobry den, tvorcom dat je nasa organizacia. 
Majte sa
M.Jasik, Prales, o.z.

Dňa po 8. 11. 2021, 7:51 Alexander Zatko napísal(a):
Dobrý deň,

Ďakujeme za súbor a povolenie na použitie dát. Ak je vaša organizácia tvorcom tých dát, tak je to všetko čo potrebujeme na to, aby sme mohli tie hranice importovať do Openstreetmap databázy a následne ich zobraziť na mape freemap.sk

Ak je však vlastníkom autorských práv iná organizácia ako vaša, budeme potrebovať aj ich výslovné povolenie. Mohli by ste mi prosím v tom prípade poslať jej názov, prípadne kontak na osobu, ktorej by sme mohli adresovať túto žiadosť?

**Comment by zdila** [comment]
Takze uz len najst niekoho kto to importne (podla pravidiel OSM) :-)

**Comment by seg-on** [comment]
Porovnal som dáta a vyhlášku a prvé ktoré som porovnal nesedí:
![image](https://user-images.githubusercontent.com/19683952/140899742-375e9aab-453d-45fb-9e24-6fb20c65de5b.png)

![image](https://user-images.githubusercontent.com/19683952/140899804-9fcbf92b-7573-43bc-94ba-d37170c95d74.png)

Podľa vyhlášky územia nemajú ochranné pásma takže toto by tiež nemalo hrať rolu.

Skúste to prípadne overiť či som nespravil niekde nejakú chybu.
Pozriem ešte nejaké

**Comment by seg-on** [comment]
Tuto je to dokonca naopak v SHP je menej ako je vyhlásené
![image](https://user-images.githubusercontent.com/19683952/140902107-a0f7e06f-7c4b-4144-9dc7-9fe62375b2a6.png)

![image](https://user-images.githubusercontent.com/19683952/140902311-11cd51da-ec53-4ede-8252-d70b05919643.png)

**Comment by alexanderzatko** [comment]
@seg-on mohol by si prosim ta uviest link na tu vyhlasku? Pokusim sa oslovit pralesy.sk o komentar.

**Comment by seg-on** [comment]
Je to druhý dokument na konci tohto článku http://www.pralesy.sk/kniznica/aktuality/171-pralesy-dostali-5-ku-konene.html

"Vlastný materiál nariadenia vlády, ktorým sa vyhlasujú prírodné rezervácie ako Pralesy Slovenska (spolu s podrobnými mapkami jednotlivých lokalít)"

**Comment by alexanderzatko** [comment]
Dostal som dalsi subor od p. Jasika, tentoraz by to mali byt len hranice PR. @zdila mozes to prosim skonvertovat?
[PR_Pralesy_Slovenska_vyhlasena_20211103.zip](https://github.com/FreemapSlovakia/freemap-operations/files/7527845/PR_Pralesy_Slovenska_vyhlasena_20211103.zip)

**Comment by seg-on** [comment]
Toto vyzerá že už sedí 👍
Skús či ti to pôjd
[PR_Pralesy_Slovenska_vyhlasena_20211103.geojson.zip](https://github.com/FreemapSlovakia/freemap-operations/files/7528834/PR_Pralesy_Slovenska_vyhlasena_20211103.geojson.zip)
e

**Comment by alexanderzatko** [comment]
Vyzera to dobre, dakujem. Na osm-sk forum som dal k diskusii navrh importu.

**Comment by alexanderzatko** [comment]
toto je - zda sa - hotove.
