### ISSUE TITLE
missing attribution - DPMŽ

### ISSUE THREAD

**Issue by Filip10** [FreemapSlovakia/freemap-operations#46]
https://mybus.dpmz.sk/

**Comment by Filip10** [comment]
Napísal som im, čakám odpoveď.

**Comment by alexanderzatko** [comment]
hmm, ja tam kredit vidim ...
<img width="355" alt="Screenshot 2023-10-17 at 18 57 52" src="https://github.com/FreemapSlovakia/freemap-operations/assets/3430677/6756a360-40a2-4b2f-a8ba-f303cb3b427f">

**Comment by Filip10** [comment]
Ja nie
![obrázok](https://github.com/FreemapSlovakia/freemap-operations/assets/25711588/60ad996f-bf26-4831-b424-537f7d958e1a)

**Comment by Filip10** [comment]
Aha, treba prijať všetky cookies, aby sa to tam zobrazilo. To je ale chyba myslím si.

**Comment by alexanderzatko** [comment]
atribuciu je vidno, aj ked su cookies zamietnute
