### ISSUE TITLE
Prilákať nových dobrovoľníkov do OSM.sk komunity

### ISSUE THREAD

**Issue by zdila** [FreemapSlovakia/freemap-operations#5]
Postup:

1. pokračovať v preklade editora iD
1. pridať Ortofotomozaiku SR do máp editora iD (blokované #3)
1. pripraviť krátke slovenské videotutoriáli ako editovať pomocou iD
1. spropagovať videá na [Freemap Facebooku](facebook.com/FreemapSlovakia/)

**Comment by alexanderzatko** [comment]
Ak by sme implementovali #15 tak v uvitacom emaili by bolo dobre spomenut existenciu Freemap zdruzenia

**Comment by zdila** [comment]
vsetky body boli viacmenej vykonane
